### ISSUE TITLE
Install on current manjaro

### ISSUE THREAD

**Issue by youcann** [saharshleo/easyROI#2]
Hi,
i got the following error when installing with pip:
```
Collecting easyroi
  Using cached EasyROI-1.0.2.tar.gz (5.7 kB)
  Using cached EasyROI-1.0.0-py3-none-any.whl (5.2 kB)
ERROR: Cannot install easyroi==1.0.0, easyroi==1.0.2 and easyroi==1.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    easyroi 1.0.3 depends on opencv-python==4.5.1.48
    easyroi 1.0.2 depends on opencv-python==4.5.1.48
    easyroi 1.0.0 depends on opencv-python==4.5.1.48
```

```
[marvin@thinkpad ~]$ python --version
Python 3.10.1
[marvin@thinkpad ~]$ uname -a
Linux thinkpad 5.10.93-1-MANJARO #1 SMP PREEMPT Thu Jan 20 09:46:07 UTC 2022 x86_64 GNU/Linux
[marvin@thinkpad ~]$ pip --version
pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)
[marvin@thinkpad ~]$
```

Any suggestions, or could you update the requirements of easyroi?

Cheers
Marvin

**Comment by saharshleo** [comment]
Hey, what is the exact command that is giving you that error? It seems you have installed multiple versions of the library. You can uninstall EasyRoi completely and then install the latest version,
Also I would recommend you to use virtual environment.

**Comment by youcann** [comment]
Hi,
i just tried to install EasyROI with `pip3 install EasyROI`

I found out that there is a conflict between the specific open-cv version you have as requirement, numpy and python 3.10. By using `pip3 install --no-dependencies EasyROI` i got no error, so maybe thats already enough.
I'll report any further errors.

Many thanks!

**Comment by saharshleo** [comment]
Oh cool, i will add that in README, Thanks
