### ISSUE TITLE
Problem in loop 

### ISSUE THREAD

**Issue by zizouk59** [saharshleo/easyROI#3]
Hello I have a Problem ! 
I putted the rectangle ROI in a loop but, it works only once, for the second time : i got the message for selecting ROI, but the window didn't show.
<img width="698" alt="Capture d’écran 2022-04-14 à 16 10 14" src="https://user-images.githubusercontent.com/103653974/163408494-e62aeafe-97c0-4dfb-b150-c004f91e51b4.png">

**Comment by saharshleo** [comment]
can you please post the code too (the loop part)

**Comment by zizouk59** [comment]
@saharshleo 
    print('img shape', img_arr.shape)
    roi_helper=EasyROI(verbose=True)
    rect_roi=roi_helper.draw_rectangle(img_arr, 1)
    print(rect_roi)
    roii=rect_roi['roi']
    print(roii)
    roii=roii[0]


    # process your img_arr here    

    #cv2.imwrite('img.png', img_arr)
    #r = cv2.selectROI("select the area",img_arr)
    #cv2.imshow("frame", r)
    #key=cv2.waitKey(0)
    #if key & 0xFF == ord('q'):
    #	cv2.destroyAllWindows()
    #cv2.imshow("img",im)
    #cv2.waitKey(10)    
    # access other keys of json
    # print(request.json['other_key'])
    x1 = roii['br_x']
    y1 = roii['br_y']
    x2 = roii['tl_x']
    y2 = roii['tl_y']
    result_dict = {'x1':x1 ,'y1': y1,'x2': x2,'y2': y2}
    print(result_dict)

**Comment by zizouk59** [comment]
this code is inside the loop (while True)

**Comment by saharshleo** [comment]
which part of code is inside while True?, 
what is your requirement exactly?, if you want to select multiple rectangles on single frame then you can pass that as a parameter in `roi_helper.draw_rectangle(frame, 2)`. Here `2` is the quantity of rectangles.

however if you want to select rectangles on different frames, below is the working code:
```py
from EasyROI import EasyROI

import cv2
from pprint import pprint


if __name__=='__main__':
    roi_helper = EasyROI(verbose=True)
    video_path = 'input/overpass.mp4'

    # Initialize cam
    cap = cv2.VideoCapture(video_path)
    assert cap.isOpened(), 'Cannot capture source'

    while(cap.isOpened()):
        ret, frame = cap.read()

        if ret == True:
            # DRAW RECTANGULAR ROI
            rect_roi = roi_helper.draw_rectangle(frame, 1)
            print("Rectangle Example:")
            pprint(rect_roi)

            frame_temp = roi_helper.visualize_roi(frame, rect_roi)
            cv2.imshow("frame", frame_temp)
            key = cv2.waitKey(0)
            if key & 0xFF == ord('q'):
                cv2.destroyAllWindows()

            if cv2.waitKey(5000) & 0xFF == 27:  # wait for ESC key for 5seconds
                break
        
        else:
            break

    cap.release()
    cv2.destroyAllWindows()
```

Output:
```sh
[DEBUG] Welcome to easyROI
[DEBUG] Entered draw_rectangle
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

Rectangle Example:
{'roi': {0: {'br_x': 395,
             'br_y': 489,
             'h': 58,
             'tl_x': 245,
             'tl_y': 431,
             'w': 150}},
 'type': 'rectangle'}
[DEBUG] Entered draw_rectangle
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

Rectangle Example:
{'roi': {0: {'br_x': 485,
             'br_y': 556,
             'h': 35,
             'tl_x': 260,
             'tl_y': 521,
             'w': 225}},
 'type': 'rectangle'}
[DEBUG] Entered draw_rectangle
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

Rectangle Example:
{'roi': {0: {'br_x': 407,
             'br_y': 588,
             'h': 89,
             'tl_x': 195,
             'tl_y': 499,
             'w': 212}},
 'type': 'rectangle'}
[DEBUG] Entered draw_rectangle
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

[DEBUG] Not all ROI's drawn
Rectangle Example:
{}
Thank You!!

```

**Comment by zizouk59** [comment]
Thank you ! 
I fixed my problem.
I was running a Flask Server with threads. 
There is an issue you can only run the selectroi on the first thread.
So, I desactivated the threads, and it works!!
